### ISSUE TITLE
Failed to load a javascript-regex package grammar

### ISSUE THREAD

**Issue by NoKtuRia** [wizard04wsu/javascript-regex#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.4
**Thrown From**: [javascript-regex](https://github.com/wizard04wsu/javascript-regex) package 2.0.0

### Stack Trace

Failed to load a javascript-regex package grammar

```
At The module '/Users/barbara/.atom/packages/javascript-regex/node_modules/tree-sitter-regex-js/build/Release/tree_sitter_regex_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/barbara/.atom/packages/javascript-regex/grammars/tree-sitter-regex-js.cson

Error: The module '/Users/barbara/.atom/packages/javascript-regex/node_modules/tree-sitter-regex-js/build/Release/tree_sitter_regex_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Users/barbara/iCloud Drive (archive) - 2/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /app.asar/node_modules/tree-sitter-regex/index.js:2:20)
    at /app.asar/node_modules/tree-sitter-regex/index.js:15:3)
    at Module.get_Module._compile (/Users/barbara/iCloud Drive (archive) - 2/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Users/barbara/iCloud Drive (archive) - 2/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Users/barbara/iCloud Drive (archive) - 2/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at new TreeSitterGrammar (/Users/barbara/iCloud Drive (archive) - 2/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3116620)
    at GrammarRegistry.createGrammar (/Users/barbara/iCloud Drive (archive) - 2/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:360231)
    at /Users/barbara/iCloud Drive (archive) - 2/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:360072
    at /Users/barbara/iCloud Drive (archive) - 2/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:581958
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
  at /packages/javascript-regex/grammars/tree-sitter-regex-js.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-debug-ui 1.0.4 
atom-ide-ui 0.13.0 
atom-python-run 0.9.7 
emmet 2.4.3 
ide-php 0.7.18 
ide-python 1.5.0 
javascript-regex 2.0.0 
my-theme-syntax 0.0.0 
php-debug 0.3.5 
Quick-JavaScript 2.2.0 
script 3.26.0 
terminal-tab 0.6.0 
theme-reel 1.2.0 
```

**Comment by wizard04wsu** [comment]
What steps do you take to get this error?

**Comment by wizard04wsu** [comment]
What version of Node and Electron is Atom using? (Help-->About Atom, Show more)

**Comment by natrius** [comment]
Atom: 1.47.0
Electron: 5.0.13
Chrome: 73.0.3683.121
Node: v12.0.0

Same error.

**Comment by wizard04wsu** [comment]
Thanks. When are you getting this error?

**Comment by natrius** [comment]
2 Times when starting up. 

First one:

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: KDE neon
**Thrown From**: [javascript-regex](https://github.com/wizard04wsu/javascript-regex) package 2.0.0


### Stack Trace

Failed to load a javascript-regex package grammar

```
At The module '/home/natrius/.atom/packages/javascript-regex/node_modules/tree-sitter-regex-js/build/Release/tree_sitter_regex_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /home/natrius/.atom/packages/javascript-regex/grammars/tree-sitter-regex-js.cson

Error: The module '/home/natrius/.atom/packages/javascript-regex/node_modules/tree-sitter-regex-js/build/Release/tree_sitter_regex_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146766)
    at /app.asar/node_modules/tree-sitter-regex/index.js:2:20)
    at /app.asar/node_modules/tree-sitter-regex/index.js:15:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:695413)
    at new TreeSitterGrammar (/usr/share/atom/resources/app/static/<embedded>:11:3114299)
    at GrammarRegistry.createGrammar (/usr/share/atom/resources/app/static/<embedded>:11:360231)
    at /usr/share/atom/resources/app/static/<embedded>:11:360072
    at /usr/share/atom/resources/app/static/<embedded>:11:581958
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
  at /packages/javascript-regex/grammars/tree-sitter-regex-js.cson:1:1
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-ide-debugger-node 0.7.3 
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-nodejs-snippets 2.1.1 
atom-pug 0.2.0 
atom-shortcuts 0.0.2 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-modules 2.3.0 
autocomplete-paths 2.12.2 
autocomplete-sql 0.5.0 
autoupdate-packages 1.3.1 
busy-signal 2.0.1 
color-picker 2.3.0 
css-grid-snippets 1.1.1 
docblockr 0.13.7 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.41 
gpp-compiler 3.0.7 
highlight-selected 0.17.0 
Hydrogen 2.14.1 
ide-php 0.7.18 
intentions 1.1.5 
javascript-regex 2.0.0 
javascript-snippets 1.2.1 
language-javascript-jsx 0.3.7 
language-pug 0.0.22 
linter 2.3.1 
linter-csslint 2.0.6 
linter-gcc 0.9.0 
linter-htmlhint 1.6.3 
linter-js-standard 7.0.0 
linter-ui-default 1.8.1 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
php-ide-serenata 5.2.0 
php-server 0.8.0 
pigments 0.40.2 
prettier-atom 0.60.0 
project-manager 3.3.8 
pug 0.8.0 
Quick-JavaScript 2.2.0 
script 3.26.0 
teletype 0.13.4 
todo-show 2.3.2 
turbo-javascript 1.4.0 
```

**Second one:** 

**Thrown From**: [javascript-regex](https://github.com/wizard04wsu/javascript-regex) package 2.0.0

### Stack Trace

Failed to load a javascript-regex package grammar

```
At The module '/home/natrius/.atom/packages/javascript-regex/node_modules/tree-sitter-regex-unicode-js/build/Release/tree_sitter_regex_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /home/natrius/.atom/packages/javascript-regex/grammars/tree-sitter-regex-unicode-js.cson

Error: The module '/home/natrius/.atom/packages/javascript-regex/node_modules/tree-sitter-regex-unicode-js/build/Release/tree_sitter_regex_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146766)
    at /app.asar/node_modules/tree-sitter-regex/index.js:2:20)
    at /app.asar/node_modules/tree-sitter-regex/index.js:15:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:695413)
    at new TreeSitterGrammar (/usr/share/atom/resources/app/static/<embedded>:11:3114299)
    at GrammarRegistry.createGrammar (/usr/share/atom/resources/app/static/<embedded>:11:360231)
    at /usr/share/atom/resources/app/static/<embedded>:11:360072
    at /usr/share/atom/resources/app/static/<embedded>:11:581958
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
  at /packages/javascript-regex/grammars/tree-sitter-regex-unicode-js.cson:1:1
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-ide-debugger-node 0.7.3 
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-nodejs-snippets 2.1.1 
atom-pug 0.2.0 
atom-shortcuts 0.0.2 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-modules 2.3.0 
autocomplete-paths 2.12.2 
autocomplete-sql 0.5.0 
autoupdate-packages 1.3.1 
busy-signal 2.0.1 
color-picker 2.3.0 
css-grid-snippets 1.1.1 
docblockr 0.13.7 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.41 
gpp-compiler 3.0.7 
highlight-selected 0.17.0 
Hydrogen 2.14.1 
ide-php 0.7.18 
intentions 1.1.5 
javascript-regex 2.0.0 
javascript-snippets 1.2.1 
language-javascript-jsx 0.3.7 
language-pug 0.0.22 
linter 2.3.1 
linter-csslint 2.0.6 
linter-gcc 0.9.0 
linter-htmlhint 1.6.3 
linter-js-standard 7.0.0 
linter-ui-default 1.8.1 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
php-ide-serenata 5.2.0 
php-server 0.8.0 
pigments 0.40.2 
prettier-atom 0.60.0 
project-manager 3.3.8 
pug 0.8.0 
Quick-JavaScript 2.2.0 
script 3.26.0 
teletype 0.13.4 
todo-show 2.3.2 
turbo-javascript 1.4.0 
```

**Comment by wizard04wsu** [comment]
Try this:
1) Click the red bug icon on the right side of the status bar.
2) In the message at the top, click the "Rebuild Packages" button.
3) Close and re-open Atom.
4) If it still gives the error, uninstall and reinstall the package.

**Comment by natrius** [comment]
Looking good, step 1-3 did the trick, no error message there anymore for me. 

Thanks wizard :)
